remote_theme: chrisrhymes/bulma-clean-theme

paginate: 5
paginate_path: "/blog/page:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "scoy"
      layout: post
      show_sidebar: true